pypro/aperitivos/urls.py
from django.urls import path

from pypro.aperitivos.views import video, indice

app_name = 'aperitivos'
urlpatterns = [
    path('<slug:slug>', video, name='video'),
    path('', indice, name='indice'),
]

pypro/base/urls.py
from django.urls import path

from pypro.base.views import home

app_name = 'base'
urlpatterns = [
    path('', home, name='home'),
]

pypro/canais/urls.py
from django.urls import path

from pypro.canais import views

app_name = 'canais'
urlpatterns = [
    path('', views.indice, name='indice'),
]

pypro/modulos/urls.py
from django.urls import path

from pypro.modulos import views

app_name = 'modulos'
urlpatterns = [
    path('<slug:slug>', views.detalhe, name='detalhe'),
    path('videos/<slug:slug>', views.video, name='video'),
    path('', views.indice, name='indice'),
]

pypro/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('contas/', include('django.contrib.auth.urls')),
    path('', include('pypro.base.urls')),
    path('aperitivos/', include('pypro.aperitivos.urls')),
    path('modulos/', include('pypro.modulos.urls')),
    path('canais/', include('pypro.canais.urls')),
]

if settings.DEBUG:
    import debug_toolbar

    urlpatterns.append(
        path('__debug__/', include(debug_toolbar.urls))
    )

pypro/aperitivos/models.py
from django.db import models
from django.urls import reverse


class Video(models.Model):
    titulo = models.CharField(max_length=32)
    slug = models.SlugField(max_length=32)
    vimeo_id = models.CharField(max_length=32)
    creation = models.DateTimeField(auto_now_add=True)

    def get_absolute_url(self):
        return reverse('aperitivos:video', args=(self.slug,))

    def __str__(self):
        return f'Video: {self.titulo}'

pypro/base/models.py
from django.contrib.auth.base_user import AbstractBaseUser, BaseUserManager
from django.contrib.auth.models import PermissionsMixin
from django.core.mail import send_mail
from django.db import models
from django.utils import timezone
from django.utils.translation import gettext_lazy as _


class UserManager(BaseUserManager):
    use_in_migrations = True

    def _create_user(self, email, password, **extra_fields):
        """
        Creates and saves a User with the given email and password.
        """
        if not email:
            raise ValueError('The given email must be set')
        email = self.normalize_email(email)
        user = self.model(email=email, **extra_fields)
        user.set_password(password)
        user.save(using=self._db)
        return user

    def create_user(self, email, password=None, **extra_fields):
        extra_fields.setdefault('is_superuser', False)
        return self._create_user(email, password, **extra_fields)

    def create_superuser(self, email, password, **extra_fields):
        extra_fields.setdefault('is_superuser', True)
        extra_fields.setdefault('is_staff', True)

        if extra_fields.get('is_superuser') is not True:
            raise ValueError('Superuser must have is_superuser=True.')
        if extra_fields.get('is_staff') is not True:
            raise ValueError('Superuser must have is_staff=True.')

        return self._create_user(email, password, **extra_fields)


class User(AbstractBaseUser, PermissionsMixin):
    """
    App base User class.

    Email and password are required. Other fields are optional.
    """

    first_name = models.CharField(_('first name'), max_length=30, blank=True)
    email = models.EmailField(_('email address'), unique=True)
    is_staff = models.BooleanField(
        _('staff status'),
        default=False,
        help_text=_('Designates whether the user can log into this admin site.'),
    )
    is_active = models.BooleanField(
        _('active'),
        default=True,
        help_text=_(
            'Designates whether this user should be treated as active. '
            'Unselect this instead of deleting accounts.'
        ),
    )
    date_joined = models.DateTimeField(_('date joined'), default=timezone.now)

    objects = UserManager()

    EMAIL_FIELD = 'email'
    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = []

    class Meta:
        verbose_name = _('user')
        verbose_name_plural = _('users')

    def clean(self):
        super().clean()
        self.email = self.__class__.objects.normalize_email(self.email)

    def get_full_name(self):
        """
        Return the first_name plus the last_name, with a space in between.
        """
        full_name = '%s' % self.first_name
        return full_name.strip()

    def get_short_name(self):
        """Return the short name for the user."""
        return self.first_name

    def email_user(self, subject, message, from_email=None, **kwargs):
        """Send an email to this user."""
        send_mail(subject, message, from_email, [self.email], **kwargs)

pypro/canais/models.py
from django.contrib.auth import get_user_model
from django.db import models


class Canal(models.Model):
    nome = models.CharField(max_length=64)
    slug = models.SlugField(max_length=64)
    inicio = models.DateField()
    fim = models.DateField()
    usuarios = models.ManyToManyField(get_user_model(), through='Inscricao')


class Inscricao(models.Model):
    data = models.DateTimeField(auto_now_add=True)
    usuario = models.ForeignKey(get_user_model(), on_delete=models.CASCADE)
    canal = models.ForeignKey(Canal, on_delete=models.CASCADE)

    class Meta:
        unique_together = [['usuario', 'canal']]
        ordering = ['canal', 'data']

pypro/modulos/models.py
from django.db import models
from ordered_model.models import OrderedModel
from django.urls import reverse


class Modulo(OrderedModel):
    titulo = models.CharField(max_length=64)
    publico = models.TextField()
    descricao = models.TextField()
    slug = models.SlugField(unique=True)

    class Meta(OrderedModel.Meta):
        pass

    def __str__(self):
        return self.titulo

    def get_absolute_url(self):
        return reverse('modulos:detalhe', kwargs={'slug': self.slug})


class Video(OrderedModel):
    titulo = models.CharField(max_length=64)
    slug = models.SlugField(unique=True)
    modulo = models.ForeignKey('Modulo', on_delete=models.PROTECT)
    order_with_respect_to = 'modulo'
    vimeo_id = models.CharField(max_length=32)

    class Meta(OrderedModel.Meta):
        pass

    def __str__(self):
        return self.titulo

    def get_absolute_url(self):
        return reverse('modulos:video', kwargs={'slug': self.slug})

pypro/aperitivos/views.py
from django.shortcuts import render, get_object_or_404

from pypro.aperitivos.models import Video


def indice(request):
    videos = Video.objects.order_by('creation').all()
    return render(request, 'aperitivos/indice.html', context={'videos': videos})


def video(request, slug):
    video = get_object_or_404(Video, slug=slug)
    return render(request, 'aperitivos/video.html', context={'video': video})

pypro/base/views.py
from django.shortcuts import render


def home(request):
    return render(request, 'base/home.html', {})

pypro/canais/views.py
from django.shortcuts import render


def indice(request):
    return render(request, 'canais/indice.html')

pypro/modulos/views.py
from django.contrib.auth.decorators import login_required
from django.shortcuts import render

from pypro.modulos import facade


def detalhe(request, slug):
    modulo = facade.encontrar_modulo(slug)
    videos = facade.listar_videos_de_modulo_ordenadas(modulo)
    return render(request, 'modulos/modulo_detalhe.html', {'modulo': modulo, 'videos': videos})


@login_required
def video(request, slug):
    video = facade.encontrar_video(slug)
    return render(request, 'modulos/video_detalhe.html', {'video': video})


def indice(request):
    ctx = {'modulos': facade.listar_modulos_com_videos()}
    return render(request, 'modulos/indice.html', ctx)

pypro/aperitivos/templates/aperitivos/indice.html
{% extends 'base/base.html' %}
{% load static %}
{% block title %}OBFS - Vídeos{% endblock title%}
{% block description %}Página com todos os videos{% endblock description %}
{% block body %}
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <h1 class="mt-4 mb-3" style="text-align:center">Lista dos Vídeos</h1>
                <ol>
                    {% for video in videos %}
                    <li><a href="{{ video.get_absolute_url }}">{{ video.titulo | default:"Faltando Título" }}</a></li>
                    {% empty %}
                    <li>Não foi encontrado nenhum vídeo</li>
                    {% endfor %}
                </ol>
            </div>
        </div>
    </div>
{% endblock body%}

pypro/aperitivos/templates/aperitivos/video.html
{% extends 'base/base.html' %}
{% load static %}
{% block title %}OBFS - Vídeo{% endblock title%}
{% block description %}Página com vídeo de demonstração{% endblock description %}
{% block body %}
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <div style="text-align:center">
                    <h1 class="mt-4 mb-3">{{ video.titulo | default:"Faltando Título" }}</h1>
                    <iframe src="https://player.vimeo.com/video/{{ video.vimeo_id }}?badge=0&amp;autopause=0&amp;player_id=0&amp;app_id=58479"
                            width="100%" height="352" frameborder="0" allow="autoplay; fullscreen; picture-in-picture"
                            allowfullscreen title="WhatsApp Video 2021-03-05 at 9.59.19 AM"></iframe>
                </div>
            </div>
        </div>
    </div>
{% endblock body%}

pypro/base/templates/base/base.html
{% load static %}
<!DOCTYPE html>
<html lang="pt-br">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <title>{% block title %}OBFS{% endblock title %}</title>

    <meta name="description" content="{% block description %}Página do curso Python Pro{% endblock description %}">
    <meta name="author" content="Oscar Borges">

    <link rel="icon" type="image/png" href="{% static 'img/favicon_obfs.png' %}"/>
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
    <link href="{% static 'css/style.css' %}" rel="stylesheet">
    <script src="{% static 'js/jquery.min.js' %}"></script>
    <script src="{% static 'js/bootstrap.min.js' %}"></script>
    <script src="{% static 'js/scripts.js' %}"></script>

</head>
<body>

<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <div class="container-fluid">
        <a class="navbar-brand" href="{% url 'base:home' %}" style="margin-left:25px;"><img
                src="{% static 'img/favicon_obfs.png' %}"
                alt="Favicon"
                width="50" height="50"/></a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent"
                aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav mr-auto">
                <li class="dropdown" style="margin-left:10px;">
                    <a class="btn btn-secondary dropdown-toggle color-card" type="button" id="dropdownMenuButton1"
                       data-bs-toggle="dropdown" aria-expanded="false"><font color="#ffa200">Modulos</font>
                    </a>
                    <div class="dropdown-menu color-card" aria-labelledby="dropdownMenuButton1">
                        {% for modulo in MODULOS %}
                        <a class="dropdown-item" href="{{modulo.get_absolute_url}}"><font color="#ffa200">
                            {{modulo.titulo}}</font></a>
                        {% endfor %}
                    </div>
                </li>
            </ul>
        {% if user.is_authenticated %}
            <ul class="navbar-nav ms-auto">
                <li class="nav-item dropdown">
                    <a class="btn btn-secondary dropdown-toggle color-card" type="button" id="dropdownMenuButton1"
                       data-bs-toggle="dropdown" aria-expanded="false"><font color="#ffa200">{{user.first_name}}</font>
                    </a>
                    <div class="dropdown-menu dropdown-menu-end color-card" aria-labelledby="dropdownMenuButton">
                        <div class="dropdown-item">
                            <a class="btn btn-danger" href="{% url 'logout' %}">Sair</a>
                        </div>
                    </div>
                </li>
            </ul>
        {% else %}
        <a class="btn btn-warning ms-auto" href="{% url 'login' %}">Entrar</a>
        {% endif %}
        </div>
    </div>
</nav>

<div class="color-page">
    {% block body %} {% endblock body %}
    {% include 'base/footer.html' with contato_email='oscar.borgesfs@gmail.com' only %}
</div>

</body>
</html>

pypro/base/templates/base/footer.html
<footer class="main-footer mt-5 pt-4 text-light">
    <div class="container pb-4">
        <div class="row">
            <div class="col">
                <h3>Entre em Contato</h3>
                <adddress>
                    +55 75 99823-9838
                    <br/>
                    <a href="mailto:{{contato_email}}" class="text-light">{{contato_email}}</a>
                </adddress>
            </div>
        </div>
    </div>
    <div class="rights pb-4">
        <div class="container">
            <div class="row">
                <div class="col">
                    {% now 'Y' %} Oscar BFS. Todos direitos reservados
                </div>
            </div>
        </div>
    </div>
</footer>

pypro/base/templates/base/home.html
{% extends 'base/base.html' %}
{% load static %}
{% block title %}OBFS - Home{% endblock title%}
{% block body %}
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <div class="jumbotron">
                    <h4 class="mt-4"> Entre para a fila de espera da equipe </h4>

                    <form action="https://herokuapp.us1.list-manage.com/subscribe/post?u=648886250d724dc2ac19df0cd&amp;id=fc9406cc37"
                          method="post" id="mc-embedded-subscribe-form" name="mc-embedded-subscribe-form"
                          class="form-row align-items-center" target="_blank" novalidate>
                        <div class="form-row align-items-center">
                            <div class="col-auto mt-2">
                                <label class="sr-only" for="mce-EMAIL">Email</label>
                                <input type="email" value="" name="EMAIL"
                                       class="form-control required bg-dark text-light" id="mce-EMAIL"
                                       placeholder="exemplo@email.com">
                            </div>
                            <div class="col-auto mt-2">
                                <label class="sr-only" for="mce-FNAME">Primeiro nome</label>
                                <input type="text" value="" name="FNAME" class="form-control bg-dark text-light"
                                       id="mce-FNAME"
                                       placeholder="Seu Nome">
                            </div>

                            <!-- real people should not fill this in and expect good things - do not remove this or risk form bot signups-->
                            <div style="position: absolute; left: -5000px;" aria-hidden="true"><input type="text"
                                                                                                      name="b_648886250d724dc2ac19df0cd_fc9406cc37"
                                                                                                      tabindex="-1"
                                                                                                      value=""></div>

                            <div class="col-auto mt-2">
                                <input type="submit" value="Salvar" name="subscribe"
                                       id="mc-embedded-subscribe" class="btn btn-primary bg-dark">
                            </div>
                        </div>
                    </form>

                </div>
                <div class="row mt-4">
                    <div class="col-md-12">
                        <div class="card color-card">
                            <h5 class="card-header">
                                <font color="#ffa200">Mais detalhes sobre o criador do site</font>
                            </h5>
                            <div class="card-body">
                                <img src="{% static 'img/Oscar_img.jpeg' %}" alt="Foto de Oscar Borges"
                                     width="200" height="200" style="float:left;margin-right:15px"/>
                                <p class="card-text text-light">
                                    <font color="#ffa200">
                                        Nome: Oscar Borges Faleta Santana <br>
                                        Idade: 18 anos <br>
                                        Formado no Ensino Médio <br>
                                        Estudante do curso Python Pro, aprendendo a fazer este site
                                    </font>
                                </p>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock body%}

pypro/canais/templates/canais/indice.html
{% extends 'base/base.html' %}
{% load static %}
{% block title %}Índice de Canais{% endblock title%}
{% block description %}Página com todos os canais {{modulo.titulo}}{% endblock description %}
{% block body %}
    <div class="container">
    {%  for modulo in modulos %}
        <div class="row">
            <div class="col-md-12">
                <h1 class="mt-4 mb-3" style="text-align:center">{{modulo.titulo}}</h1>
                <dl>
                    <dt>Público</dt>
                    <dd>{{modulo.publico}}</dd>
                    <dt>Descrição</dt>
                    <dd>{{modulo.descricao}}</dd>
                </dl>
                <h2>Vídeos</h2>
                <ol>
                    {% for video in modulo.videos %}
                    <li><a href="{{ video.get_absolute_url }}"><font color="#000000">{{video.titulo}}</font></a></li>
                    {% endfor %}
                </ol>
            </div>
        </div>
    {% endfor %}
    </div>
{% endblock body%}

pypro/modulos/templates/modulos/indice.html
{% extends 'base/base.html' %}
{% load static %}
{% block title %}{{modulo.titulo}}{% endblock title%}
{% block description %}Página com detalhes do módulo {{modulo.titulo}}{% endblock description %}
{% block body %}
    <div class="container">
    {%  for modulo in modulos %}
        <div class="row">
            <div class="col-md-12">
                <h1 class="mt-4 mb-3" style="text-align:center">{{modulo.titulo}}</h1>
                <dl>
                    <dt>Público</dt>
                    <dd>{{modulo.publico}}</dd>
                    <dt>Descrição</dt>
                    <dd>{{modulo.descricao}}</dd>
                </dl>
                <h2>Vídeos</h2>
                <ol>
                    {% for video in modulo.videos %}
                    <li><a href="{{ video.get_absolute_url }}"><font color="#000000">{{video.titulo}}</font></a></li>
                    {% endfor %}
                </ol>
            </div>
        </div>
    {% endfor %}
    </div>
{% endblock body%}

pypro/modulos/templates/modulos/modulo_detalhe.html
{% extends 'base/base.html' %}
{% load static %}
{% block title %}{{modulo.titulo}}{% endblock title%}
{% block description %}Página com detalhes do módulo {{modulo.titulo}}{% endblock description %}
{% block body %}
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <h1 class="mt-4 mb-3" style="text-align:center">{{modulo.titulo}}</h1>
                <dl>
                    <dt>Público</dt>
                    <dd>{{modulo.publico}}</dd>
                    <dt>Descrição</dt>
                    <dd>{{modulo.descricao}}</dd>
                </dl>
                <h2>Vídeos</h2>
                <ol>
                    {% for video in videos %}
                    <li><a href="{{ video.get_absolute_url }}"><font color="#000000">{{video.titulo}}</font></a></li>
                    {% endfor %}
                </ol>
            </div>
        </div>
    </div>
{% endblock body%}

pypro/modulos/templates/modulos/video_detalhe.html
{% extends 'base/base.html' %}
{% load static %}
{% block title %}OBFS - Vídeo{% endblock title%}
{% block description %}Página com vídeo de demonstração{% endblock description %}
{% block body %}
    <nav aria-label="breadcrumb">
        <div class="color-card">
            <ol class="breadcrumb" style="margin-left:40px;">
                <li class="breadcrumb-item"><a href="#"><font color="#ffa200">Home</font></a></li>
                <li class="breadcrumb-item"><a href="/modulos/"><font color="#ffa200">Modulos</font></a></li>
                <li class="breadcrumb-item">
                    <a href="{{video.modulo.get_absolute_url}}"><font color="#ffa200">{{video.modulo.titulo}}</font></a>
                </li>
                <li class="breadcrumb-item active" aria-current="page"><font color="#ffa200">{{video.titulo}}</font>
                </li>
            </ol>
        </div>
    </nav>
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <div style="text-align:center">
                    <h1 class="mt-4 mb-3">{{ video.titulo | default:"Faltando Título" }}</h1>
                    <iframe src="https://player.vimeo.com/video/{{ video.vimeo_id }}?badge=0&amp;autopause=0&amp;player_id=0&amp;app_id=58479"
                            width="100%" height="352" frameborder="0" allow="autoplay; fullscreen; picture-in-picture"
                            allowfullscreen title="WhatsApp Video 2021-03-05 at 9.59.19 AM"></iframe>
                </div>
            </div>
        </div>
    </div>
{% endblock body%}